[ffmpeg]
ffprobe=/scratch/p/pd511/conda/envs/dpinterview/bin/ffprobe
ffmpeg=/scratch/p/pd511/conda/envs/dpinterview/bin/ffmpeg

[general]
data_root=/data/sbdp/PHOENIX
output_root=/scratch/p/pd511/dpinterview_outputs
temp_dir=/scratch/p/pd511/tmp
study=CAMI
self_heal=True

[orchestration]
num_to_decrypt=50
snooze_time_seconds=900
openface_max_instances=5

[singularity]
singularity_image_path=/data/itp/sw/feature-extraction/feature-extraction.sif
bind_params=/scratch:/scratch

[crawler]
hash_files=False
redcap_metadata_path=/PHShome/pd511/scratch/data/CAMILongitudinalCollection_DataDictionary_2026-04-07.csv
av_runsheet_path=/PHShome/pd511/scratch/data/CAMILongitudinalColl_DATA_2026-04-09_1454_no_v2.csv
form_data_study_pattern=*/redcap/processed/*_interviews.csv

[dropbox]
# Only needed if you run dropbox sync
key_file=/scratch/p/pd511/keys/dropbox.key

[postgresql]
host=127.0.0.1
port=55432
database=dpinterview_v1
user=pipeline
password=piedpiper

[openface_db]
host=localhost
port=55432
database=openface_db
user=pipeline
password=piedpiper

[report_generation]
fau_h_gap_idx=5,9,14
bin_size=30
bins_per_page=60
anonymize=False
report_version = v_test

[decryption]
# Only needed if interviews are encrypted
key_file=/scratch/p/pd511/keys/PHOENIX.key

[split-streams]
default_role=subject
left_role=subject
right_role=interviewer

[openface]
openblas_num_threads=32
openface_max_retry=3

[openface_features]
int_cols=frame,face_id
bool_cols=success
time_cols=timestamp
sample_csv_file=/scratch/p/pd511/projects/dpinterview/sample/openface/features.csv

[metrics]
consolidated_csv_path=/scratch/p/pd511/metrics/metrics.csv
consolidated_html_path=/scratch/p/pd511/metrics/metrics.html
html_script_path=/scratch/p/pd511/projects/dpinterview/pipeline/assets/js_scripts/bls_script.js
html_report_path=/scratch/p/pd511/metrics/metrics_report.html

[logging]
# scripts
init_db=/scratch/p/pd511/logs/init_db.log

# crawlers
import_study_metadata=/scratch/p/pd511/logs/import_study_metadata.log
import_interview_files=/scratch/p/pd511/logs/import_interview_files.log
import_transcript_files=/scratch/p/pd511/logs/import_transcript_files.log

# runners
decryption=/scratch/p/pd511/logs/01_decryption.log

fetch_video=/scratch/p/pd511/logs/01_fetch_video.log
metadata=/scratch/p/pd511/logs/02_metadata.log
video-qqc=/scratch/p/pd511/logs/03_video-qqc.log
split-streams=/scratch/p/pd511/logs/04_split-streams.log
openface=/scratch/p/pd511/logs/05_openface.log
openface_qc=/scratch/p/pd511/logs/06_openface_qc.log

load_openface=/scratch/p/pd511/logs/08_load_openface.log

pipeline.runners.study_specific.bls.21_transcript_quick_qc=/scratch/p/pd511/logs/21_transcript_quick_qc.log

report_generation=/scratch/p/pd511/logs/70_report_generation.log
pipeline.runners.71_dropbox_sync=/scratch/p/pd511/logs/71_dropbox_sync.log

pipeline.runners.study_specific.bls.72_clinical_scores_import=/scratch/p/pd511/logs/72_bls_clinical_scores_import.log

pipeline.runners.73_consolidate_metrics=/scratch/p/pd511/logs/73_consolidate_metrics.log
pipeline.runners.75_generate_cover_report=/scratch/p/pd511/logs/75_generate_cover_report.log

pipeline.runners.99_wiper=/scratch/p/pd511/logs/99_wiper.log

fetch_audio=/scratch/p/pd511/logs/21_fetch_audio.log

crawlers.import_data_dictionary=/scratch/p/pd511/logs/06_data_dictionary.log
import_form_data=/scratch/p/pd511/logs/07_form_data.log
import_expected_interviews=/scratch/p/pd511/logs/08_expected_interviews.log