name: feat-extract
channels:
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - alsa-lib=1.2.10
  - aom=3.6.1
  - asttokens=2.4.0
  - attr=2.5.1
  - attrs=23.2.0
  - aws-c-auth=0.7.7
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.8
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.14
  - aws-c-io=0.13.36
  - aws-c-mqtt=0.9.10
  - aws-c-s3=0.4.1
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.24.7
  - aws-sdk-cpp=1.11.182
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.20.1
  - ca-certificates=2024.7.4
  - cairo=1.18.0
  - certifi=2024.7.4
  - chardet=5.2.0
  - cni=1.0.1
  - cni-plugins=1.3.0
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.1.0
  - cssselect2=0.2.1
  - cycler=0.11.0
  - datasets=2.19.1
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.7.0
  - decorator=5.1.1
  - dill=0.3.8
  - dropbox=11.36.2
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=6.0.0
  - filelock=3.12.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.42.1
  - freeglut=3.2.2
  - freetype=2.12.1
  - freetype-py=2.3.0
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - fzf=0.48.1
  - gettext=0.21.1
  - gflags=2.2.2
  - glib=2.78.0
  - glib-tools=2.78.0
  - glog=0.6.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - graphite2=1.3.13
  - gst-plugins-base=1.22.6
  - gstreamer=1.22.6
  - h2=4.1.0
  - harfbuzz=8.2.1
  - hdf5=1.14.2
  - hpack=4.0.0
  - huggingface_hub=0.23.4
  - hyperframe=6.0.1
  - icu=73.2
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - ipykernel=6.25.2
  - ipython=8.15.0
  - jasper=4.2.4
  - jedi=0.19.0
  - jinja2=3.1.2
  - jq=1.7.1
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libarchive=3.5.2
  - libarrow=14.0.1
  - libarrow-acero=14.0.1
  - libarrow-dataset=14.0.1
  - libarrow-flight=14.0.1
  - libarrow-flight-sql=14.0.1
  - libarrow-gandiva=14.0.1
  - libarrow-substrait=14.0.1
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.4.0
  - libdeflate=1.20
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.1.0
  - libgcrypt=1.10.1
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.78.0
  - libglu=9.0.0
  - libgomp=13.1.0
  - libgoogle-cloud=2.12.0
  - libgpg-error=1.47
  - libgrpc=1.59.2
  - libhwloc=2.9.2
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.52.0
  - libnl=3.9.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.24
  - libopencv=4.8.1
  - libopenvino=2023.1.0
  - libopenvino-auto-batch-plugin=2023.1.0
  - libopenvino-auto-plugin=2023.1.0
  - libopenvino-hetero-plugin=2023.1.0
  - libopenvino-intel-cpu-plugin=2023.1.0
  - libopenvino-intel-gpu-plugin=2023.1.0
  - libopenvino-ir-frontend=2023.1.0
  - libopenvino-onnx-frontend=2023.1.0
  - libopenvino-paddle-frontend=2023.1.0
  - libopenvino-pytorch-frontend=2023.1.0
  - libopenvino-tensorflow-frontend=2023.1.0
  - libopenvino-tensorflow-lite-frontend=2023.1.0
  - libopus=1.3.1
  - libparquet=14.0.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=16.2
  - libprotobuf=4.24.4
  - libre2-11=2023.09.01
  - libseccomp=2.4.4
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.43.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libsystemd0=254
  - libtasn1=4.19.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libva=2.20.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.6.0
  - libxml2=2.12.7
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - lxml=4.9.3
  - lz4-c=1.9.4
  - lzo=2.10
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mkl=2022.2.1
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpg123=1.31.3
  - mpmath=1.3.0
  - multidict=6.0.5
  - multiprocess=0.70.16
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.4.20240210
  - nest-asyncio=1.5.6
  - nettle=3.8.1
  - networkx=3.1
  - nspr=4.35
  - nss=3.94
  - ocl-icd=2.3.1
  - ocl-icd-system=1.0.0
  - oniguruma=6.9.9
  - opencv=4.8.1
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.3.1
  - orc=1.9.0
  - p11-kit=0.24.1
  - packaging=23.1
  - pandas=2.1.0
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.2.1
  - pixman=0.42.2
  - platformdirs=3.10.0
  - ply=3.11
  - postgresql=16.2
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.13
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - py-opencv=4.8.1
  - pyarrow=14.0.1
  - pyarrow-hotfix=0.6
  - pycairo=1.25.0
  - pyparsing=3.0.9
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-xxhash=3.4.1
  - python_abi=3.11
  - pytorch=2.0.1
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qt-main=5.15.8
  - rdma-core=52.0
  - re2=2023.09.01
  - readline=8.2
  - reportlab=4.0.6
  - requests=2.31.0
  - rlpycairo=0.2.0
  - s2n=1.3.56
  - safetensors=0.4.3
  - setuptools=68.1.2
  - singularity=3.8.6
  - sip=6.7.11
  - six=1.16.0
  - snappy=1.1.10
  - squashfs-tools=4.6.1
  - stack_data=0.6.2
  - stone=3.3.1
  - svglib=1.5.1
  - svt-av1=1.7.0
  - sympy=1.12.1
  - tbb=2021.10.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tmux=3.3a
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.9.0
  - tree=2.1.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzcode=2023c
  - tzdata=2023c
  - ucx=1.15.0
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - wheel=0.41.2
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.39
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zoxide=0.9.4
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - about-time==4.2.1
      - absl-py==1.4.0
      - alive-progress==3.1.4
      - annotated-types==0.7.0
      - anyio==4.3.0
      - apprise==1.7.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - black==23.7.0
      - bleach==6.1.0
      - blinker==1.8.2
      - bootstrap-flask==2.4.0
      - cachetools==5.3.1
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - click==8.1.7
      - cryptease==0.2.0
      - cryptography==41.0.3
      - defusedxml==0.7.1
      - dnspython==2.5.0
      - fastjsonschema==2.19.1
      - flake8==6.1.0
      - flask==3.0.3
      - flask-wtf==1.2.1
      - flatbuffers==23.5.26
      - fqdn==1.5.1
      - fsspec==2023.9.0
      - gast==0.4.0
      - google-auth==2.23.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grapheme==0.6.0
      - greenlet==3.0.0
      - grpcio==1.58.0
      - h11==0.14.0
      - h5py==3.9.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.4
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - joblib==1.3.2
      - json5==0.9.24
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.4
      - jupyter-server==2.13.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.4
      - jupyterlab-widgets==3.0.9
      - keras==2.13.1
      - libclang==16.0.6
      - libtmux==0.37.0
      - loguru==0.7.2
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.3
      - notebook-shim==0.2.4
      - numpy==1.24.3
      - oauthlib==3.2.2
      - ollama==0.2.1
      - opt-einsum==3.3.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - pathspec==0.11.2
      - prometheus-client==0.20.0
      - protobuf==4.24.3
      - psycopg2-binary==2.9.9
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycodestyle==2.11.0
      - pycparser==2.21
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pyflakes==3.1.0
      - pygments==2.16.1
      - pymongo==4.6.1
      - python-json-logger==2.0.7
      - referencing==0.34.0
      - regex==2023.8.8
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.5.3
      - rpds-py==0.18.0
      - rsa==4.9
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - seaborn==0.13.0
      - send2trash==1.8.2
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==2.0.21
      - termcolor==2.3.0
      - terminado==0.18.1
      - threadpoolctl==3.2.0
      - tokenizers==0.13.3
      - tqdm==4.66.1
      - transformers==4.33.1
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - urllib3==1.26.16
      - webcolors==1.13
      - websocket-client==1.7.0
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.9
      - wrapt==1.15.0
      - wtforms==3.1.2
